--- #YAML:1.0
name:       Acme-KeyboardMarathon
version:    1.17
abstract:   How far have your fingers ran?
author:
    - Phil Pollard <bennie@cpan.org>
    - Efrain Klein <efrain.klein@gmail.com>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:               5.008001
    Carp:               0
    Test::Simple:       0
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=Acme-KeyboardMarathon
    repository:
        type:  git
        url:   git://github.com/bennie/perl-Acme-KeyboardMarathon.git
        web:   http://github.com/bennie/perl-Acme-KeyboardMarathon
no_index:
    directory:
        - t
        - inc
provides:
    Acme::KeyboardMarathon:
        file: lib/Acme/KeyboardMarathon.pm
        version: 1.17
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
