---
abstract: 'How far have your fingers ran?'
author:
  - 'Phil Pollard <bennie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-KeyboardMarathon
no_index:
  directory:
    - t
    - inc
    - t
provides:
  Acme::KeyboardMarathon:
    file: lib/Acme/KeyboardMarathon.pm
    version: 1.18
requires:
  Carp: 0
  Test::More: 0
  Test::Simple: 0
  perl: 5.008001
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Acme-KeyboardMarathon
  repository: git://github.com/bennie/perl-Acme-KeyboardMarathon.git
version: 1.18
