abstract: How far have your fingers ran?
author:
  Phil Pollard <bennie@cpan.org>
  Efrain Klein <efrain.klein@gmail.com>
distribution_type: module
name: ACME-KeyboardMarathon
generated_by: Phil Pollard <bennie@cpan.org>
license: perl
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
resources:
  license: http://dev.perl.org/licenses/
version: 1.14
version_from: lib/ACME/LeyboardMarathon.pm
